"""Private single-user journey data. Additive tables; no physiology or goal writes.

Reads use the application's existing private API boundary. Explicit writes are
revision-checked and never queued, generated by a model, or forwarded to a provider.
"""
from __future__ import annotations

from datetime import date, datetime, timedelta, timezone
import json
from typing import Annotated, Callable, Literal
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

from fastapi import APIRouter, Depends, HTTPException, Query, Response
from pydantic import BaseModel, ConfigDict, Field as PydanticField
from pydantic.alias_generators import to_camel
from sqlalchemy import Column, Text, update
from sqlalchemy.exc import IntegrityError
from sqlmodel import SQLModel, Field, Session, select

try:
    from .health_v2_models import HealthSleepSessionDB, HealthSleepStageDB
except ImportError:
    from health_v2_models import HealthSleepSessionDB, HealthSleepStageDB


class JourneyDayDB(SQLModel, table=True):
    __tablename__ = "journey_day"
    date: str = Field(primary_key=True)
    revision: int = 0
    payload_json: str = Field(default="{}", sa_column=Column(Text, nullable=False))
    updated_at: str | None = None


class JourneyPreferencesDB(SQLModel, table=True):
    __tablename__ = "journey_preferences"
    id: str = Field(default="default", primary_key=True)
    revision: int = 0
    payload_json: str = Field(default="{}", sa_column=Column(Text, nullable=False))
    updated_at: str | None = None


class Camel(BaseModel):
    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True, extra="forbid")


Rating = Annotated[int, PydanticField(strict=True, ge=1, le=5)]
Focus = Literal["sleep", "movement", "strength", "nutrition", "stress"]


class CheckIn(Camel):
    energy: Rating | None = None
    soreness: Rating | None = None
    stress: Rating | None = None
    training_intent: Literal["plan", "rest"] | None = None
    note: Annotated[str, PydanticField(max_length=400)] | None = None
    stress_minute: Annotated[int, PydanticField(strict=True, ge=0, le=1439)] | None = None
    reflection: Annotated[str, PydanticField(max_length=400)] | None = None
    nutrition_reviewed: Annotated[bool, PydanticField(strict=True)] = False
    nutrition_fingerprint: Annotated[str, PydanticField(pattern=r"^[0-9a-f]{16}$")] | None = None


class CheckInPatch(CheckIn):
    expected_revision: Annotated[int, PydanticField(strict=True, ge=0)]


class Preferences(Camel):
    wake_time: Annotated[str, PydanticField(pattern=r"^([01]\d|2[0-3]):[0-5]\d$")] | None = None
    sleep_minutes: Annotated[int, PydanticField(strict=True, ge=300, le=660)] | None = None
    wind_down_minutes: Annotated[int, PydanticField(strict=True, ge=0, le=120)] = 30
    focus: Focus | None = None


class PreferencesPatch(Preferences):
    expected_revision: Annotated[int, PydanticField(strict=True, ge=0)]


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _day_payload(row: JourneyDayDB) -> dict:
    data = json.loads(row.payload_json)
    reviewed_at = data.pop("nutritionReviewedAt", None)
    return {**CheckIn.model_validate(data).model_dump(by_alias=True), "date": row.date,
            "revision": row.revision, "updatedAt": row.updated_at, "nutritionReviewedAt": reviewed_at}


def _preferences_payload(row: JourneyPreferencesDB | None) -> dict:
    return {**Preferences.model_validate(json.loads(row.payload_json) if row else {}).model_dump(by_alias=True),
            "revision": row.revision if row else 0}


def _save(db: Session, model, key: str, expected: int, changes: dict, *, reset=False):
    """Optimistic compare-and-swap. Reset retains a revision tombstone (no ABA race)."""
    row = db.get(model, key)
    if (row.revision if row else 0) != expected:
        raise HTTPException(409, "This entry changed. Reload before saving again.")
    prior = json.loads(row.payload_json) if row and not reset else {}
    prior.update(changes)
    stamp = _utc_now()
    if model is JourneyDayDB and "nutritionReviewed" in changes:
        prior["nutritionReviewedAt"] = stamp if changes["nutritionReviewed"] else None
    payload = json.dumps(prior, ensure_ascii=False)
    if row:
        identity = model.date if model is JourneyDayDB else model.id
        result = db.execute(update(model).where(identity == key, model.revision == expected).values(
            revision=expected + 1, payload_json=payload, updated_at=stamp))
        if result.rowcount != 1:
            db.rollback()
            raise HTTPException(409, "This entry changed. Reload before saving again.")
    else:
        kwargs = {"date" if model is JourneyDayDB else "id": key}
        db.add(model(**kwargs, revision=1, payload_json=payload, updated_at=stamp))
    try:
        db.commit()
    except IntegrityError as exc:
        db.rollback()
        raise HTTPException(409, "This entry changed. Reload before saving again.") from exc
    db.expire_all()
    return db.get(model, key)


def _night(row: HealthSleepSessionDB) -> dict:
    return {"date": row.local_end_date, "startUtc": row.start_utc, "endUtc": row.end_utc,
            "startOffsetSeconds": row.start_offset_seconds, "endOffsetSeconds": row.end_offset_seconds,
            "minutesAsleep": row.minutes_asleep, "minutesAwake": row.minutes_awake,
            "provenance": row.provenance, "sourceId": row.source_id}


def _parse_time(value: str) -> datetime:
    parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    if parsed.tzinfo is None:
        raise ValueError("An offset is required")
    return parsed


def create_journey_router(get_db: Callable) -> APIRouter:
    router = APIRouter(prefix="/journey", tags=["journey"])

    def no_cache(response: Response):
        response.headers["Cache-Control"] = "no-store"

    router.dependencies.append(Depends(no_cache))

    def valid_day(value: date, tz: str) -> None:
        try:
            today = datetime.now(ZoneInfo(tz)).date()
        except (ZoneInfoNotFoundError, ValueError) as exc:
            raise HTTPException(422, "Unsupported time zone") from exc
        if value > today or value < today - timedelta(days=35):
            raise HTTPException(422, "Check-ins must be within the last 35 days, not in the future")

    @router.get("")
    def snapshot(start_date: date = Query(alias="startDate"), end_date: date = Query(alias="endDate"), db: Session = Depends(get_db)):
        if not 0 <= (end_date - start_date).days <= 34:
            raise HTTPException(422, "Request one to 35 calendar days")
        rows = db.exec(select(JourneyDayDB).where(JourneyDayDB.date >= start_date.isoformat(), JourneyDayDB.date <= end_date.isoformat())).all()
        return {"version": 1, "startDate": start_date.isoformat(), "endDate": end_date.isoformat(),
                "days": [_day_payload(row) for row in rows], "preferences": _preferences_payload(db.get(JourneyPreferencesDB, "default"))}

    @router.patch("/days/{day}")
    def save_day(day: date, body: CheckInPatch, time_zone: str = Query(default="America/New_York", alias="timeZone"), db: Session = Depends(get_db)):
        valid_day(day, time_zone)
        changes = body.model_dump(by_alias=True, exclude_unset=True, exclude={"expected_revision"})
        if not changes:
            raise HTTPException(422, "No check-in changes supplied")
        row = _save(db, JourneyDayDB, day.isoformat(), body.expected_revision, changes)
        return _day_payload(row)

    @router.delete("/days/{day}")
    def clear_day(day: date, expected_revision: int = Query(ge=0, alias="expectedRevision"), db: Session = Depends(get_db)):
        # Erasure is allowed for old entries as well. Notes are removed, not soft-hidden.
        return _day_payload(_save(db, JourneyDayDB, day.isoformat(), expected_revision, {}, reset=True))

    @router.patch("/preferences")
    def save_preferences(body: PreferencesPatch, db: Session = Depends(get_db)):
        changes = body.model_dump(by_alias=True, exclude_unset=True, exclude={"expected_revision"})
        prior = _preferences_payload(db.get(JourneyPreferencesDB, "default"))
        merged = {**prior, **changes}
        if bool(merged["wakeTime"]) != bool(merged["sleepMinutes"]):
            raise HTTPException(422, "Choose both a wake time and sleep opportunity, or clear both")
        if not changes:
            raise HTTPException(422, "No preference changes supplied")
        return _preferences_payload(_save(db, JourneyPreferencesDB, "default", body.expected_revision, changes))

    @router.get("/sleep/{day}")
    def sleep_detail(day: date, db: Session = Depends(get_db)):
        # Matches the existing experimental sleep evaluator's preferred main-session selection.
        rows = db.exec(select(HealthSleepSessionDB).where(
            HealthSleepSessionDB.local_end_date >= (day - timedelta(days=14)).isoformat(),
            HealthSleepSessionDB.local_end_date <= day.isoformat(),
            HealthSleepSessionDB.is_deleted == False,  # noqa: E712
            HealthSleepSessionDB.session_kind == "MAIN_SLEEP",
        ).limit(1001)).all()
        if len(rows) > 1000:
            raise HTTPException(503, "Sleep detail window is too large")
        priority = {"google_wearables_reconciled": 2, "source_raw": 1}
        preferred = {}
        for row in rows:
            prior = preferred.get(row.local_end_date)
            if prior is None or (priority.get(row.provenance, 0), row.id) > (priority.get(prior.provenance, 0), prior.id):
                preferred[row.local_end_date] = row
        row = preferred.get(day.isoformat())
        stages = []
        status = "missing"
        if row:
            raw = db.exec(select(HealthSleepStageDB).where(HealthSleepStageDB.session_id == row.id).order_by(HealthSleepStageDB.start_utc).limit(1001)).all()
            if raw:
                try:
                    start, end = _parse_time(row.start_utc), _parse_time(row.end_utc)
                    previous_end = start
                    if len(raw) > 1000 or end <= start:
                        raise ValueError("Invalid sleep span")
                    for stage in raw:
                        a, b = _parse_time(stage.start_utc), _parse_time(stage.end_utc)
                        if not (start <= a < b <= end) or a < previous_end:
                            raise ValueError("Overlapping or out-of-range stages")
                        previous_end = b
                        stages.append({"type": stage.stage_type, "startUtc": stage.start_utc, "endUtc": stage.end_utc})
                    status = "available"
                except ValueError:
                    stages, status = [], "invalid"
        return {"date": day.isoformat(), "night": _night(row) if row else None, "stages": stages, "timelineStatus": status,
                "history": [_night(preferred[key]) for key in sorted(preferred) if key < day.isoformat()]}

    return router
